[package]
name = "black-box"
version = "0.2.0"
authors = ["Trevor Lovell <trevorlovelldesign@gmail.com>"]
edition = "2018"
description = "Puzzle game about expirementation."

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "main", features = ["ui", "gltf", "animation"] }
log = { version = "0.4.8", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.6.4"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
