[package]
name = "black-box"
version = "0.2.0"
authors = ["Trevor Lovell <trevorlovelldesign@gmail.com>"]
edition = "2018"
description = "Puzzle game about expirementation."

[dependencies]
amethyst = {version = "0.15.3", features = ["no-slow-safety-checks", "gltf", "animation"]}
log = { version = "0.4.8", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.6.4"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
